language: python
python:
  - 3.8
script:
  - pytest

before_install:
  - "pip install pandas"
  - "pip install pyspark"

notifications:
  email:
    recipients:
      - joao.je.nisa@gmail.com
    on_success: always
    on_failure: always